config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :messages, only:  :create
    resource :likes, only: [:create, :destroy]

    collection do
      get :search, :comment_ranking
    end
    member do
      get :like_user
    end

  end

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get :followings, :followers, :follow_review, :good_review
    end
  end
  get 'items/category/:category_id' => 'items#category'
  get 'ranking' => 'items#ranking'
  get 'pv_ranking' => 'items#pv_ranking'
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_item
  def create
    like = current_user.likes.new(item_id: @item.id)
    like.save

    @item.create_notification_by(current_user)
    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.js
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, item_id: @item.id).destroy
  end
  private
  def set_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
          <%if user_signed_in?%> 
          <div class="good-btn">
            <% if current_user.liked_by?(@item) %>
              <%= link_to  item_likes_path(@item), method: :delete,remote: true do %>
                <i class="fas fa-thumbs-up"></i>
                
              <%end%>  
            <% else %>
              <%= link_to  item_likes_path(@item),method: :post,remote: true do  %>
                <i class="far fa-thumbs-up"></i>
              <%end%>  
            <% end %>
          </div> 
          <%= link_to like_user_item_path(@item.id),class:"link" do %>
          <div class="item-count">
            <%= @item.likes.count%>
          </div> 
          <%end%>
          <%else %>
          <div class="heart">
            <i class="fas fa-thumbs-up"></i>
          </div>
          <div class="item-count">
            <%= @item.likes.count%>
          </div> 
          <%end%>

app/views/likes/_like2.html.erb
          <%if user_signed_in?%>
          <div class="good-btn2">
            <% if current_user.liked_by?(@item.id) %>
              <%= link_to  item_likes_path(@item), method: :delete,remote: true do %>
                <i class="fas fa-thumbs-up ii"></i>
                
              <%end%>  
            <% else %>
              <%= link_to  item_likes_path(@item),method: :post,remote: true do  %>
                <i class="far fa-thumbs-up ii"></i>
              <%end%>  
            <% end %>
          </div> 
          <%end%>
          
          
          

app/views/likes/create.js.erb
document.getElementById("like-link-<%= @item.id %> ").innerHTML = '<%= j(render partial: 'likes/like', locals: { item: @item}) %>'

document.getElementById("lik-link-<%= @item.id %> ").innerHTML = '<%= j(render partial: 'likes/like2', locals: { item: @item}) %>'

app/views/likes/destroy.js.erb
document.getElementById("like-link-<%= @item.id %> ").innerHTML = '<%= j(render partial: 'likes/like', locals: { item: @item}) %>'

document.getElementById("lik-link-<%= @item.id %> ").innerHTML = '<%= j(render partial: 'likes/like2', locals: { item: @item}) %>'