config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :messages, only:  :create
    resource :likes, only: [:create, :destroy]

    collection do
      get :search, :comment_ranking
    end
    member do
      get :like_user
    end

  end

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get :followings, :followers, :follow_review, :good_review
    end
  end
  get 'items/category/:category_id' => 'items#category'
  get 'ranking' => 'items#ranking'
  get 'pv_ranking' => 'items#pv_ranking'
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true

  has_one_attached :image
  has_many :items, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item

  has_many :followers,
           class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :followings,
           class_name: 'Relationship',
           foreign_key: 'following_id',
           dependent: :destroy,
           inverse_of: :following
  has_many :following_users, through: :followers, source: :following
  has_many :follower_users, through: :followings, source: :follower
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy

  def follow(other_user_id)
    followers.create(following_id: other_user_id)
  end

  def following?(other_user)
    following_users.include?(other_user)
  end

  def unfollow(other_user_id)
    followers.destroy(following_id: other_user_id)
  end

  def liked_by?(item_id)
    likes.where(item_id: item_id).exists?
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]

  def show
    @followings = @user.following_users
  end

  def index
    @users = User.all.page(params[:page]).per(16)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followings
    @followings = @user.following_users.page(params[:page]).per(16)
  end

  def followers
    @followers = @user.follower_users.page(params[:page]).per(16)
  end

  def follow_review
    @followings = @user.following_users
  end

  def good_review
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<%if user_signed_in?%>
<%unless @user == current_user%>
  <% if current_user.following?(@user)%>
    <%=button_to "フォロー中",relationship_path,method: :delete ,class: "fllowig-btn" %>
  <%else%>
    <%= form_for(@user.followers.build) do |f| %>
      <%= hidden_field_tag :follow_id, @user.id %>
      <%= f.submit "フォロー" ,class: "follow-btn" %>
    <% end %>
  <%end%>
<%end%>
<%end%>

app/views/users/follow_review.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-item">
          <div class="user-nick">
            <h1>フォローユーザーレビュー一覧</h1> 
          </div>      
        </div>
        <div class="user_matome">
            <%=link_to "いいねしたレビュー",good_review_user_path ,class:"follow"  %>
            <%=link_to "#{@user.nickname}のホームへ", user_path, class:"good-r" %>
          </div>
        <%if user_signed_in? && current_user.id == @user.id%>
        <div class="myrank">
           
        </div> 
        <%end%>  
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            follow user review
          </div>
          <ul class='item-lists'>
      
            <% @followings.each do |user| %>
            <%user.items.page(params[:page]).per(16).each do |item|%>
            <li class='list'>
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
                <%= item.name%>
                
              </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              <div class="good-county">
                    <i class="fas fa-thumbs-up"></i>      <%=item.likes.count%>
              </div> 
              </div>
              
              
              
              <% end %>
              
            </li>
            <%end%>
            <%= paginate user.items.page(params[:page]).per(16) %>
            <% end %>
          </ul>
          
         
        </div>
        <%= link_to new_item_path, class: 'item-btn' do %>
        <span class='item-btn-text'>Post Review</span>
        <%= image_tag 'icon_camera.png' , size: '79x50' ,class: "item-btn-icon" %>
        <% end %>  
          
</div>




 <%= render "shared/footer" %>

app/views/users/followers.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="follower-list">
          <h1>フォロワー</h1>   
        </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            user list
          </div>

       
          <ul class='item-lists'>
      
            <% @followers.each do |user| %>
            <div class="comment-profile">
                <div class="profile">
                  <% if user.image.attached? %>
                    <%= image_tag user.image, class: "user-icon3" %>
                  <% else %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon3" %>
                  <% end %>
                </div>
                <div  class="name-file">
                  <%= link_to user.nickname, user_path(user.id) ,class: "message-nickname" %>
                  
                </div>
            </div>
            <%end%>
          </ul>
          
          <%= link_to t("button.back"), user_path %>
          <%= paginate @followers %>
          
        </div> 
          
</div>

<%=render "shared/footer"%>

app/views/users/followings.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="follow-list">
          <h1>フォロー中</h1>   
        </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            user list
          </div>

       
          <ul class='item-lists'>
      
            <% @followings.each do |user| %>
            <div class="comment-profile">
                <div class="profile">
                  <% if user.image.attached? %>
                    <%= image_tag user.image, class: "user-icon3" %>
                  <% else %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon3" %>
                  <% end %>
                </div>
                <div  class="name-file">
                  <%= link_to user.nickname, user_path(user.id) ,class: "message-nickname" %>
                  
                </div>
            </div>
            <%end%>
          </ul>
          
          <%= link_to t("button.back"), user_path %>
          <%= paginate @followings %>
          
        </div> 
          
</div>

<%=render "shared/footer"%>

app/views/users/good_review.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-item">
          <div class="user-nick">
            <h1>マイグッドレビュー一覧</h1> 
          </div>      
        </div>
        <div class="user_matome">
            <%=link_to "フォローユーザーレビュー",follow_review_user_path ,class:"follow"  %>
            <%=link_to "#{@user.nickname}のホームへ", user_path, class:"good-r" %>
          </div>
        <%if user_signed_in? && current_user.id == @user.id%>
        <div class="myrank">
           
        </div> 
        <%end%>  
        <div class='item-contents'>
          

          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            my good review
          </div>
          
          <ul class='item-lists'>
      
            <%@user.like_items.page(params[:page]).per(16).each do |post|%>
            
            <li class='list'>
              <%= link_to item_path(post.id),class:"link" do %>
              <div class='item-info'>
                
                <%= post.name%>
                
            </div>
              <div class='item-img-content'>
                
                <%if post.image.attached? %>
                  <%= image_tag post.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if post.user.image.attached? %>
                      <%=link_to user_path(post.user.id),class:"user-icon4" do %>
                        <%= image_tag post.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(post.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to post.user.nickname, user_path(post.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=post.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              <div class="good-county">
                    <i class="fas fa-thumbs-up"></i>      <%=post.likes.count%>
              </div> 
              </div>
              
              
              <% end %>
              
            </li>
          
            <% end %>
            <%= paginate @user.page(params[:page]).per(16) %>
          </ul>
          
          
        </div> 
        <%= link_to new_item_path, class: 'item-btn' do %>
        <span class='item-btn-text'>Post Review</span>
        <%= image_tag 'icon_camera.png' , size: '79x50' ,class: "item-btn-icon" %>
        <% end %> 
          
</div>




 <%= render "shared/footer" %>

app/views/users/good_review.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-item">
          <div class="user-nick">
            <h1>マイグッドレビュー一覧</h1> 
          </div>      
        </div>
        <div class="user_matome">
            <%=link_to "フォローユーザーレビュー",follow_review_user_path ,class:"follow"  %>
            <%=link_to "#{@user.nickname}のホームへ", user_path, class:"good-r" %>
          </div>
        <%if user_signed_in? && current_user.id == @user.id%>
        <div class="myrank">
           
        </div> 
        <%end%>  
        <div class='item-contents'>
          

          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            my good review
          </div>
          
          <ul class='item-lists'>
      
            <%@user.like_items.page(params[:page]).per(16).each do |post|%>
            
            <li class='list'>
              <%= link_to item_path(post.id),class:"link" do %>
              <div class='item-info'>
                
                <%= post.name%>
                
            </div>
              <div class='item-img-content'>
                
                <%if post.image.attached? %>
                  <%= image_tag post.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if post.user.image.attached? %>
                      <%=link_to user_path(post.user.id),class:"user-icon4" do %>
                        <%= image_tag post.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(post.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to post.user.nickname, user_path(post.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=post.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              <div class="good-county">
                    <i class="fas fa-thumbs-up"></i>      <%=post.likes.count%>
              </div> 
              </div>
              
              
              <% end %>
              
            </li>
          
            <% end %>
            <%= paginate @user.items.page(params[:page]).per(16) %>
          </ul>
          
          
        </div> 
        <%= link_to new_item_path, class: 'item-btn' do %>
        <span class='item-btn-text'>Post Review</span>
        <%= image_tag 'icon_camera.png' , size: '79x50' ,class: "item-btn-icon" %>
        <% end %> 
          
</div>




 <%= render "shared/footer" %>

app/views/users/index.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-lists">
          <h1>ユーザー一覧</h1>   
        </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            user list
          </div>

       
          <ul class='item-lists'>
      
            <%@users.each do |user|%>
            <div class="comment-profile">
                <div class="profile">
                <% if user.image.attached? %>
                  <%=link_to user_path(user.id),class:"user-icon4" do %>
                    <%= image_tag user.image, class: "user-icon4" %>
                  <%end%>  
                <% else %>
                  <%=link_to user_path(user.id) ,class:"user-icon4" do %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                  <%end%>
                <% end %>
              </div>
                <div  class="name-file">
                  <%= link_to user.nickname, user_path(user.id) ,class: "message-nickname" %>
                </div>
               
            </div>
            <%end%>
          </ul>
          
          
          <%= paginate @users %>
          
        </div> 
          
</div>

<%=render "shared/footer"%>

app/views/users/show.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-item">
          <div class="user-nick">
            <%="#{@user.nickname}のホーム" %> 
          </div>  
          <div class="follow">
            <%= render "follow_form" %>
             
            <p class="follow-count">
              <%= link_to "#{@user.followers.count} #{User.human_attribute_name("フォロー")}", followings_user_path %> <%= link_to "#{@user.followings.count} #{User.human_attribute_name("フォロワー")}", followers_user_path %>
            </p> 
            <%if user_signed_in? && current_user.id == @user.id%>
            <%=link_to "アカウント情報の編集",edit_user_registration_path(current_user), class:"edi-user"%>
            <%end%> 
            <% if user_signed_in? && current_user.id == @user.id%>
            <li><%= link_to '通知', notifications_path, class: "footer-link" %></li>
            <%end%>
            <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to '管理者用ページ', rails_admin_path, class: "footer-link" %></li>
            <% end %>
          </div>     
        </div>
        <div class="user_matome">
            <%=link_to "フォローユーザーレビュー",follow_review_user_path ,class:"follow"  %>
            <%=link_to "いいねしたレビュー", good_review_user_path, class:"good-r" %>
        </div>
        
        <div class="myrank">
           
        </div> 
         
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            user reviews
          </div>
          <ul class='item-lists'>
      
            <%@user.items.page(params[:page]).per(16).each do |item|%>
            
            <li class='list'>
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
              <%= item.name%>
                
            </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              <div class="good-county">
              <i class="fas fa-thumbs-up"></i>    <%=item.likes.count%>
            </div> 
              </div>
              
              
              
              
              <% end %>
            </li>
            
            <%end%>
            <%= paginate @user.items.page(params[:page]).per(16) %>
          </ul>
         
        </div> 
        <%= link_to new_item_path, class: 'item-btn' do %>
        <span class='item-btn-text'>Post Review</span>
        <%= image_tag 'icon_camera.png' , size: '79x50' ,class: "item-btn-icon" %>
        <% end %> 
          
</div>




 <%= render "shared/footer" %>