config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :messages, only:  :create
    resource :likes, only: [:create, :destroy]

    collection do
      get :search, :comment_ranking
    end
    member do
      get :like_user
    end

  end

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get :followings, :followers, :follow_review, :good_review
    end
  end
  get 'items/category/:category_id' => 'items#category'
  get 'ranking' => 'items#ranking'
  get 'pv_ranking' => 'items#pv_ranking'
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
  <div class='footer'>
      <div class='footer-contents'>
        <div class='sound-details'>
          <h2 class='footer-content-head'>一覧</h2>
          <ul>
            <li><%= link_to 'カテゴリー一覧', root_path, class: "footer-link" %></li>
            <li><%= link_to 'ユーザー一覧', users_path, class: "footer-link" %></li>
          </ul>
        </div>
        <div class='sound-details'>
          <h2 class='footer-content-head'>ランキング</h2>
          <ul>
            <li><%= link_to 'レビューランキング', ranking_path, class: "footer-link" %></li>
            <li><%= link_to 'アクセス数ランキング', pv_ranking_path, class: "footer-link" %></li>
            <li><%= link_to 'コメント数ランキング', comment_ranking_items_path, class: "footer-link" %></li>           
          </ul>
        </div>
        <div class='sound-details'>
          <h2 class='footer-content-head'>通知</h2>
          <ul>
            <% if user_signed_in?%>
            <li><%= link_to '通知', notifications_path, class: "footer-link" %></li>
            <%end%>
            
            
          </ul>
        </div>
      </div>
      <%= link_to image_tag("soundreview.png", class:"foot-icon"), "/" %>
      <p>© soundreview</p>
  </div>

app/views/shared/_header.html.erb
<header class="top-page-header">
      <div class="search-bar-contents">
        <%= link_to image_tag("soundreview.png", class:"top-icon"), "/" %>

        <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form",id: "niko") do |f| %>
          <%= f.text_field :keyword,id:"result-div", placeholder: "ボタンをクリックで音声検索", class: "input-box" %>
          <div id="start-btn2"  class="search-button2">
            <%= image_tag "maic.png", class:"search-icon2" %>
           
          </div>
          <button id="start-btn"  class="search-button">
            <%= image_tag "search.png", class:"search-icon" ,id: "img-btn" %>
           
          </button>
        <% end %>
      </div>
      <div class='nav'>
        <ul class='lists-right'>
          <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <div class="profile">
                    <% if current_user.image.attached? %>
                      <%=link_to user_path(current_user.id),class:"user-icon4" do %>
                        <%= image_tag current_user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(current_user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
            <div class="right-head">
              <div>
              <%= link_to current_user.nickname, user_path(current_user.id), class: "post" %>
              </div>
              <div>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class:"post" %>
              </div>
            </div>
          </div>
          <% else %>
          <div class="user_sign grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
          <% end %>
        </ul>
      </div>

</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  
  <%= link_to image_tag("soundreview.png", class:"second-footer-logo"), "/" %>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("soundreview.png", class:"second-logo"), "/" %>
</header>