config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :messages, only:  :create
    resource :likes, only: [:create, :destroy]

    collection do
      get :search, :comment_ranking
    end
    member do
      get :like_user
    end

  end

  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      get :followings, :followers, :follow_review, :good_review
    end
  end
  get 'items/category/:category_id' => 'items#category'
  get 'ranking' => 'items#ranking'
  get 'pv_ranking' => 'items#pv_ranking'
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  is_impressionable counter_cache: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  belongs_to :user
  has_one_attached :image
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  has_many :notifications, dependent: :destroy

  def self.search(search)
    if search != ''
      Item.includes(:user).joins(:user).where([
                                                'name LIKE(?) OR text LIKE(?) OR users.nickname LIKE (?) OR minicategory LIKE(?) ', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
                                              ])

    else
      Item.includes(:user).order('created_at DESC')
    end
  end

  with_options presence: true do
    validates :name
    validates :category_id
    validates :audio
  end

  validates :category_id, numericality: { other_than: 1 }

  mount_uploader :audio, AudiofileUploader

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      item_id: id,
      visited_id: user_id,
      action: 'like'
    )
    notification.save if notification.valid?
  end

  def create_notification_message!(current_user, message_id)
    temp_ids = Message.select(:user_id).where(item_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_message!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_message!(current_user, message_id, user_id) if temp_ids.blank?
  end

  def save_notification_message!(current_user, message_id, visited_id)
    notification = current_user.active_notifications.new(
      item_id: id,
      message_id: message_id,
      visited_id: visited_id,
      action: 'message'
    )
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :category, :ranking, :pv_ranking, :comment_ranking]
  before_action :set_item, only: [:show, :edit, :update, :destroy,:like_user]
  impressionist actions: [:show]

  def new
    @item = Item.new
    @category = params[:category_id]
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @items = Item.includes(:user).all.order('created_at DESC').limit(12)
    @ranks = Item.find(Like.group(:item_id).order('count(item_id) DESC').limit(5).pluck(:item_id))
  end

  def show
    @message = Message.new
    @messages = @item.messages.includes(:user).order('created_at DESC')
    @messages.each do |message|
      @mess = message
    end
    @like = Like.new
    @views = @item.impressions.size
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def category
    @movie = Item.where(category_id: '2').page(params[:page]).per(16)
    @anime = Item.where(category_id: '3').page(params[:page]).per(16)
    @music = Item.where(category_id: '4').page(params[:page]).per(16)
    @book = Item.where(category_id: '5').page(params[:page]).per(16)
    @other = Item.where(category_id: '6').page(params[:page]).per(16)
    @category = params[:category_id]
  end

  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(16)
  end

  def ranking
    @ranks = Item.find(Like.group(:item_id).order('count(item_id) DESC').limit(5).pluck(:item_id))
  end

  def comment_ranking
    @comment_ranks = Item.find(Message.group(:item_id).order('count(item_id) DESC').limit(5).pluck(:item_id))
  end

  def pv_ranking
    @pv_ranking = Item.find(Impression.group(:impressionable_id).order('count(impressionable_id) desc').limit(5).pluck(:impressionable_id))
  end
  def like_user
    
  end

  private

  def item_params
    params.require(:item).permit(:name, :text, :audio, :category_id, :url, :image, :minicategory).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_lists(items)
    html = ''
    items.each do |item|
      html += render(partial: 'item', locals: {item: item})
    end
    return raw(html)
  end
end

app/views/items/_item.html.erb
<li class='list'>
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
                <%= item.name%>
                
                
              </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%> 
                 
              </div>
              <div class="profile-all">
              <div class="profile2">
                <% if item.user.image.attached? %>
                  <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                    <%= image_tag item.user.image, class: "user-icon4" %>
                  <%end%>  
                <% else %>
                  <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                  <%end%>
                <% end %>
                
              </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
                
              
              </div>
              <%= link_to like_user_item_path(item.id),class:"link" do %>
              <div class="good-county">
                    <i class="fas fa-thumbs-up"></i>      <%=item.likes.count%>
              </div> 
              <%end%>
              
              <% end %>
            </li>

app/views/items/comment_ranking.html.erb
<%=render "shared/header"%>
<div class='main'>
  <div class="ranking-title">
      <h1>コメント数ランキング</h1>
         
  </div>
  <div class="rank-container">
    <div class='item-contents'>
      <h2 class='title'>Pick Up</h2>
      <div class="subtitle" >
        top comment reviews
      </div>
    </div>
    <% lastFavorite = 0 %>
    <% j=1 %>
    <% @comment_ranks.each.with_index(1) do |item, i| %>
      <%if i==1 %>
        <%lastFavorite = item.messages.count %>
      <%end%>  
      <%if item.messages.count!= lastFavorite%>
        <% j=i %>
        <div class="rank-box">
    
        
              <ul class='rank-lists'>
                <div class="ranks">
                  <li class="rank">
                    <%= j %>位  
                  </li>
                  <li class="good-count">
                    コメント数：<%=item.messages.count%>
                  </li>
              
                </div>  
                <li class='list'>
            
                  <%= link_to item_path(item.id),class:"link" do %>
                  <div class='item-info'>
                
                    <%= item.name%>
                
                  </div>
                  <div class='item-img-content'>
                
                    <%if item.image.attached? %>
                      <%= image_tag item.image, class: "item-img"  %>
                    <%else%>
                      <%= image_tag 'soundreview2.png', class: "item-img"  %>
                   <%end%>  
                  </div>
                  <div class="profile-all">
                  <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
                  <div class="item-create">
                    <div class="item-user-name">
                      <%= link_to item.user.nickname, user_path(item.user.id) %>
                    </div> 
                    <div class="created_at" >
                        <%=item.created_at.strftime('%Y/%m/%d')%>
                    </div>
              
                  </div>
                  </div>
                  
                  
              
              
                  <% end %>
                </li>
           
              </ul>
          <%lastFavorite = item.messages.count%>
        </div>
      <%else%>
      <%lastFavorite = item.messages.count%>
      <div class="rank-box">
    
        
          <ul class='rank-lists'>
            <div class="ranks">
              <li class="rank">
                <%= j %>位  
              </li>
              <li class="good-count">
                コメント数：<%=item.messages.count%>
              </li>
              
            </div>
            <li class='list'>
            
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
                <%= item.name%>
                
              </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
                  <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
                  <div class="item-create">
                    <div class="item-user-name">
                      <%= link_to item.user.nickname, user_path(item.user.id) %>
                    </div> 
                    <div class="created_at" >
                        <%=item.created_at.strftime('%Y/%m/%d')%>
                    </div>
              
                  </div>
                  </div>
              
              
              
              <% end %>
            </li>
           
          </ul>
      <%end%>   
      </div>    
    <% end %>
  </div>
</div>  
<%=render "shared/footer"%>

app/views/items/index.html.erb
    
    <%=render "shared/header"%>
    <div class='main'>
      <div class="main-class">
        <div class="categories">
          <h1>Category</h1>
          <div class="category">
            <%= link_to "映画", "/items/category/2" ,class:"category-name"%>
          </div>  
          <div class="category">
            <%= link_to "アニメ", "/items/category/3" ,class:"category-name"%>
          </div>  
          <div class="category">
            <%= link_to "音楽", "/items/category/4",class:"category-name" %>
          </div>  
          <div class="category">
            <%= link_to "本", "/items/category/5",class:"category-name" %>
          </div>  
          <div class="category">
            <%= link_to "その他", "/items/category/6" ,class:"category-name"%>
          </div> 
           
        </div>
    
        <video autoplay muted playsinline src="/videos/sound1.mp4",playsinline autoplay loop ></video>
      </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            new reviews
          </div>
          <ul class='item-lists'>
      
            <%= item_lists(@items) %>
              
          </ul>
          
          
        </div> 


        
      <%= link_to new_item_path, class: 'item-btn' do %>
      <span class='item-btn-text'>Post Review</span>
      <%= image_tag 'icon_camera.png' , size: '79x50' ,class: "item-btn-icon" %>
      <% end %>     
    </div>
      
    
    <%= render "shared/footer" %>

    
   

app/views/items/like_user.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="user-lists">
          <h1>レビューにいいねしたユーザー</h1>   
        </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            user list
          </div>

       
          <ul class='item-lists'>
      
            <%@item.like_users.each do |user|%>
            <div class="comment-profile">
                <div class="profile">
                <% if user.image.attached? %>
                  <%=link_to user_path(user.id),class:"user-icon4" do %>
                    <%= image_tag user.image, class: "user-icon4" %>
                  <%end%>  
                <% else %>
                  <%=link_to user_path(user.id) ,class:"user-icon4" do %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                  <%end%>
                <% end %>
              </div>
                <div  class="name-file">
                  <%= link_to user.nickname, user_path(user.id) ,class: "message-nickname" %>
                </div>
               
            </div>
            <%end%>
          </ul>
          
          
         
          
        </div> 
          
</div>

<%=render "shared/footer"%>

app/views/items/pv_ranking.html.erb
<%=render "shared/header"%>
<div class='main'>
  <div class="ranking-title">
      <h1>レビューアクセスランキング</h1>
         
  </div>
  <div class="rank-container">
    <div class='item-contents'>
      <h2 class='title'>Pick Up</h2>
      <div class="subtitle" >
        top access reviews
      </div>
    </div>
    <% lastFavorite = 0 %>
    <% j=1 %>
    <% @pv_ranking.each.with_index(1) do |item, i| %>
      <%if i==1 %>
        <%lastFavorite = item.impressions.size %>
      <%end%>  
      <%if item.impressions.size!= lastFavorite%>
        <% j=i %>
        <div class="rank-box">
    
        
              <ul class='rank-lists'>
                <div class="ranks">
                  <li class="rank">
                    <%= j %>位  
                  </li>
                  <li class="good-count">
                    アクセス数：<%=item.impressions.size%>
                  </li>
              
                </div>  
                <li class='list'>
            
                  <%= link_to item_path(item.id),class:"link" do %>
                  <div class='item-info'>
                
                    <%= item.name%>
                
                  </div>
                  <div class='item-img-content'>
                
                    <%if item.image.attached? %>
                      <%= image_tag item.image, class: "item-img"  %>
                    <%else%>
                      <%= image_tag 'soundreview2.png', class: "item-img"  %>
                   <%end%>  
                  </div>
                  <div class="profile-all">
              <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              </div>
                  
              
              
                  <% end %>
                </li>
           
              </ul>
          <%lastFavorite = item.impressions.size%>
        </div>
      <%else%>
      <%lastFavorite = item.impressions.size%>
      <div class="rank-box">
    
        
          <ul class='rank-lists'>
            <div class="ranks">
              <li class="rank">
                <%= j %>位  
              </li>
              <li class="good-count">
                アクセス数：<%=item.impressions.size%>
              </li>
              
            </div>
            <li class='list'>
            
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
                <%= item.name%>
                
              </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              </div>
              
              
              
              <% end %>
            </li>
           
          </ul>
      <%end%>   
      </div>    
    <% end %>
  </div>
</div>  
<%=render "shared/footer"%>

app/views/items/ranking.html.erb
<%=render "shared/header"%>
<div class='main'>
  <div class="ranking-title">
      <h1>グッドレビューランキング</h1>
         
  </div>
  <div class="rank-container">
    <div class='item-contents'>
      <h2 class='title'>Pick Up</h2>
      <div class="subtitle" >
        top good reviews
      </div>
    </div>
    <% lastFavorite = 0 %>
    <% j=1 %>
    
    <% @ranks.each.with_index(1) do |item, i| %>
      <%if i==1 %>
        <%lastFavorite = item.likes.count %>
      <%end%>  
      <%if item.likes.count != lastFavorite%>
        <% j=i %>
        <div class="rank-box">
    
        
              <ul class='rank-lists'>
                <div class="ranks">
                  <li class="rank">
                    <%= j %>位  
                  </li>
                  <%= link_to like_user_item_path(item.id),class:"link" do %>
                  <li class="good-count">
                    いいね数：<%=item.likes.count%>
                  </li>
                  <%end%>
              
                </div>  
                <li class='list'>
            
                  <%= link_to item_path(item.id),class:"link" do %>
                  <div class='item-info'>
                
                    <%= item.name%>
                
                  </div>
                  <div class='item-img-content'>
                
                    <%if item.image.attached? %>
                      <%= image_tag item.image, class: "item-img"  %>
                    <%else%>
                      <%= image_tag 'soundreview2.png', class: "item-img"  %>
                   <%end%>  
                  </div>
                  <div class="profile-all">
                  <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
                  <div class="item-create">
                    <div class="item-user-name">
                      <%= link_to item.user.nickname, user_path(item.user.id) %>
                    </div> 
                    <div class="created_at" >
                        <%=item.created_at.strftime('%Y/%m/%d')%>
                    </div>
              
                  </div>
                  </div>
                  
              
              
                  <% end %>
                </li>
           
              </ul>
          <%lastFavorite = item.likes.count%>
        </div>
      <%else%>
      <%lastFavorite = item.likes.count%>
      <div class="rank-box">
    
        
          <ul class='rank-lists'>
            <div class="ranks">
              <li class="rank">
                <%= j %>位  
              </li>
              <%= link_to like_user_item_path(item.id),class:"link" do %>
              <li class="good-count">
                いいね数：<%=item.likes.count%>
              </li>
              <%end%>
              
            </div>
            <li class='list'>
            
              <%= link_to item_path(item.id),class:"link" do %>
              <div class='item-info'>
                
                <%= item.name%>
                
              </div>
              <div class='item-img-content'>
                
                <%if item.image.attached? %>
                  <%= image_tag item.image, class: "item-img"  %>
                <%else%>
                  <%= image_tag 'soundreview2.png', class: "item-img"  %>
                <%end%>  
              </div>
              <div class="profile-all">
              <div class="profile2">
                    <% if item.user.image.attached? %>
                      <%=link_to user_path(item.user.id),class:"user-icon4" do %>
                        <%= image_tag item.user.image, class: "user-icon4" %>
                      <%end%>  
                    <% else %>
                      <%=link_to user_path(item.user.id) ,class:"user-icon4" do %>
                        <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                      <%end%>
                    <% end %>
                  </div>
              <div class="item-create">
                <div class="item-user-name">
                  <%= link_to item.user.nickname, user_path(item.user.id) %>
                </div> 
                <div class="created_at" >
                    <%=item.created_at.strftime('%Y/%m/%d')%>
                </div>
              
              </div>
              </div>
              
              
              
              <% end %>
            </li>
           
          </ul>
      <%end%>   
      </div>    
    <% end %>
    
  </div>
</div>  

<%=render "shared/footer"%>

app/views/items/search.html.erb
<%=render "shared/header"%>
<div class='main'>
        <div class="search">
          <h1>search results</h1>   
        </div>
        <div class='item-contents'>
          <h2 class='title'>Pick Up</h2>
          <div class="subtitle" >
            movie reviews
          </div>
          <ul class='item-lists'>
      
            <%= item_lists(@items) %>
          </ul>
          
          <%= paginate @items %>
        </div> 
          
</div>

<%=render "shared/footer"%>

app/views/items/show.html.erb
    <%= render "shared/header" %>
    
    <div class="item-show">

      <div class="item-box">
        <div class="item-profile">

         <div class="cate-name"> 
           <span class="show-category">Category</span><br/>
           <%if @item.category.name== "映画" %>
            <%= link_to "#{@item.category.name}", "/items/category/2" ,class: "another-itom" %><br/><p class="mini-name"><%=@item.minicategory%><p>
           <%elsif @item.category.name== "アニメ" %>
            <%= link_to "#{@item.category.name}", "/items/category/3" ,class: "another-itom" %><br/><p class="mini-name"><%=@item.minicategory%><p>
           <%elsif @item.category.name== "音楽" %>
            <%= link_to "#{@item.category.name}", "/items/category/4" ,class: "another-itom" %><br/><p class="mini-name"><%=@item.minicategory%><p>
           <%elsif @item.category.name== "本" %>
            <%= link_to "#{@item.category.name}", "/items/category/5" ,class: "another-itom" %><br/><p class="mini-name"><%=@item.minicategory%><p>
           <%elsif @item.category.name== "その他" %>
            <%= link_to "#{@item.category.name}", "/items/category/6" ,class: "another-itom" %><br/><p class="mini-name"><%=@item.minicategory%><p>
           <%end%>
         </div>
        
       </div> 
        <h2 class="name">
          <%= @item.name %>
        </h2>
        
        <div class="item-content">
          <div class="item-img-content">
            <%if @item.image.attached? %>
              <%= image_tag @item.image, class: "item-box-img"  %>
            <%else%>
              <%= image_tag 'soundreview2.png', class: "item-box-img"  %>
            <%end%>
          </div>
        </div> 
       
        <div class="item-user">
            
            <div class="profile">
                <% if @item.user.image.attached? %>
                  <%=link_to user_path(@item.user.id),class:"user-icon4" do %>
                    <%= image_tag @item.user.image, class: "user-icon4" %>
                  <%end%>  
                <% else %>
                  <%=link_to user_path(@item.user.id) ,class:"user-icon4" do %>
                    <%= image_tag "willy.png", alt: "user-icon", class: "user-icon4" %>
                  <%end%>
                <% end %>
              </div>
            
            <div class="item-user-name">
              <%= link_to @item.user.nickname, user_path(@item.user.id) %>
            </div> <br/>
            
            
            
            <div class="good" id="like-link-<%= @item.id %> ">
          
              <%= render partial: 'likes/like', locals: { item: @item} %>
               
         
            </div> 
              <%= link_to  "https://twitter.com/share?url=おすすめレビュー #{@item.name}   #{request.url}", title: 'Twitter', target: '_blank',class:"twitter" do%>
                <i class="fab fa-twitter"></i>
              <%end%> 
        </div> 
        <div>
          <%=@item.created_at.strftime('%Y/%m/%d')%>
        </div>  
          
       
        <div class="item-price-box">
          <audio src= "<%= "#{@item.audio}" %>" controls="" preload="metadata">
                  
          </audio>
          
        </div>
        <%if @item.text.present?%>
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-item">テキストレビュー</th>
              <td class="detail-value detail-text" id="text"><%= @item.text %></td>
            </tr>
          </tbody>

        </table>
       
        <%end%>
         
        <%if @item.url.present?%>
        <div class="url">
          外部URL<br/>
          <div class="item-urll">
            <%=link_to "関連サイトへ", @item.url %>
          </div>  
        </div>
        <%end%>
        
              
      
        
        <%if user_signed_in?%>
        <%if current_user.id==@item.user_id %>
        <div class="edit-btn">
          <div class="edit">
            <%= link_to "レビューの編集", edit_item_path, method: :get, class: "item-red-btn" %>
          </div>  
          <div class="delete">
            <%= link_to "削除", item_path, method: :delete, class:"item-destroy" %>
          </div>
        </div>  
        <%end%>
        <%end%>
       
        
        
      </div>
      
      
      <div class="comment-box">
        
        
        <% if user_signed_in? %>
        <h2 class="items-sell-title">コメントを入力</h2>
          <%= form_with model:[@item,@message], local: true do |f| %>
          <div class="comment-explain">
            <div class="weight-bold-comment w-comment">
              ・文字コメント
            </div>
            <%= f.text_area :comment, class:"items-comment", id:"comment-info"%>
            <div class="weight-comment w-comment">
              ・音声コメント
            </div>
            <%= f.file_field :audiocomment , class:"sound-comment" %>
          </div>
          <div class="sell-btn-contents">
            <%= f.submit "投稿する" ,class:"comment-btn" %>
          </div>
          <%end%>
        <% else %>
          <strong><p>※ コメントの投稿には新規登録/ログインが必要です </p></strong>
        <% end %>
        <%if @mess.present?%>
        <tbody id="message">
           <%= render 'messages/index', messages: @messages %>
          
        </td>
        <%else%>
          <h2 class="items-comment-title">コメント</h2>
        <%end%>

      <%if @item.category.name== "映画" %>
        <%= link_to "#{@item.category.name}をもっと見る", "/items/category/2" ,class: "another-item" %>
      <%elsif @item.category.name== "アニメ" %>
        <%= link_to "#{@item.category.name}をもっと見る", "/items/category/3" ,class: "another-item" %>
      <%elsif @item.category.name== "音楽" %>
        <%= link_to "#{@item.category.name}をもっと見る", "/items/category/4" ,class: "another-item" %>
      <%elsif @item.category.name== "本" %>
        <%= link_to "#{@item.category.name}をもっと見る", "/items/category/5" ,class: "another-item" %>
      <%elsif @item.category.name== "その他" %>
        <%= link_to "#{@item.category.name}をもっと見る", "/items/category/6" ,class: "another-item" %>  
      <%end%>    
    </div>
    <%if user_signed_in?%> 
    <div class="good2" id="lik-link-<%= @item.id %> ">
          
      <%= render partial: 'likes/like2', locals: { item: @item} %>
         
    </div>
    <%end%> 
  <%= render "shared/footer" %>